server:
  port: 9012

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/java_demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_UUID
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
